---

default_vo_generic_dn_ca_cern: &default_vo_generic_dn_ca_cern '/DC=ch/DC=cern/CN=CERN Grid Certification Authority'
default_vo_generic_dn_server_primary: &default_vo_generic_dn_server_primary '/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch'
default_vo_generic_dn_server_secondary: &default_vo_generic_dn_server_secondary '/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch'
default_vo_generic_server_primary: &default_vo_generic_server_primary 'voms2.cern.ch'
default_vo_generic_server_secondary: &default_vo_generic_server_secondary 'lcg-voms2.cern.ch'

## defaults for supported_virtual_organizations
default_vo_alice: &default_vo_alice
  - name: alice
  - server: *default_vo_generic_server_primary
    port: '15000'
    dn: *default_vo_generic_dn_server_primary
    ca_dn: *default_vo_generic_dn_ca_cern
  - server: *default_vo_generic_server_secondary
    port: '15001'
    dn: *default_vo_generic_dn_server_secondary
    ca_dn: *default_vo_generic_dn_ca_cern

default_vo_ops: &default_vo_ops
  - name: ops
  - server: *default_vo_generic_server_primary
    port: '15009'
    dn: *default_vo_generic_dn_server_primary
    ca_dn: *default_vo_generic_dn_ca_cern
  - server: *default_vo_generic_server_secondary
    port: '15009'
    dn: *default_vo_generic_dn_server_secondary
    ca_dn: *default_vo_generic_dn_ca_cern

default_vo_dteam: &default_vo_dteam
  - server: *default_vo_generic_server_primary
    port: '15001'
    dn: *default_vo_generic_dn_server_primary
    ca_dn: *default_vo_generic_dn_ca_cern
  - server: *default_vo_generic_server_secondary
    port: '15001'
    dn: *default_vo_generic_dn_server_secondary
    ca_dn: *default_vo_generic_dn_ca_cern

##default values for group names
default_group_alice_name: &default_group_alice_name alice
default_group_alicesgm_name: &default_group_alicesgm_name atlas
default_group_dteam_name: &default_group_dteam_name dteam
default_group_dteamsgm_name: &default_group_dteamsgm_name dteamsgm
default_group_ops_name: &default_group_ops_name ops
default_group_opssgm_name: &default_group_opssgm_name opssgm

##default values for groups
default_group_alice: &default_group_alice
  

default_group_dteam: &default_group_dteam
  gid: 2688
  name: *default_group_dteam_name
  accepted_voms_extensions:

default_group_dteamsgm: &default_group_dteamsgm
  gid: 2680
  name: *default_group_dteamsgm_name
  priority_group: sgm
  accepted_voms_extensions:

default_group_ops: &default_group_ops
  gid: 45000
  name: *default_group_ops_name
  accepted_voms_extensions:

default_group_opssgm: &default_group_opssgm
  gid: 46001
  name: *default_group_opssgm_name
  priority_group: sgm
  accepted_voms_extensions: '/alice/ROLE='

  ## default pool accounts

default_pool_account_dteam: &default_pool_account_dteam
  base_name: 'dteam'
  initial_uid: '18118'
  users_num: '10'
  primary_group: *default_group_dteam_name
  
default_pool_account_dteamsgm: &default_pool_account_dteamsgm
  base_name: 'sgmdtm'
  initial_uid: '60501'
  users_num: '5'
  primary_group: *default_group_dteamsgm_name
  secondary_group: *default_group_dteam_name
    
default_pool_account_dteam_with_sgm: &default_pool_account_dteam_with_sgm
  - *default_pool_account_dteam 
  - *default_pool_account_dteamsgm

default_pool_account_ops: &default_pool_account_ops  
  base_name: 'ops'
  initial_uid: '45001'
  users_num: '10'
  primary_group: *default_group_ops_name

default_pool_account_opssgm: &default_pool_account_opssgm
  base_name: 'sgmops'
  initial_uid: '60701'
  users_num: '10'
  primary_group: *default_group_ops_name
  secondary_group: *default_group_opssgm_name

default_pool_account_ops_with_sgm: &default_pool_account_ops_with_sgm
  - *default_pool_account_ops
  - *default_pool_account_opssgm

## Variable declaration:
variables:
  - &amazon_ip_address 18.184.37.92
  - &digitalocean_ip_address 167.99.253.118  

site: 
  name: ''
  email: ''
  latitude: ''
  longitude: ''
  location: ''
  description: ''
  website: ''
  support_website: ''
  support_email: ''
  security_email: ''
  grid: '' #site_other_grid: str(), wlcg, egi,osg
  tier: ''

preferred_tech_stack:
  level_1_configuration: puppet
  level_2_configuration: puppet
  container_orchestration: docker-swarm
  container: docker
  
site_infrastructure: 
  - hostname: ec2-18-184-37-92.eu-central-1
    domain: compute.amazonaws.com
    ip_address: 104.236.95.32


lightweight_components:
  - type: compute_element
    repository_url: "https://github.com/WLCG-Lightweight-Sites/wlcg_lightweight_site_ce_cream"
    nodes:
      - node: lw-site-droplet-0
        container_count: 1
      - node: ec2-18-184-37-92.eu-central-1
        container_count: 2
    preferred_tech_stack:
      level_2_configuration: yaim
    config:
      - cream-info:
          #wn_list: str()
          #users_conf: str()
          #groups_conf: str()
          edgusers: str()
          mysql_password: str()
          #site_name: str()
          #site_email: str()
          #site_lat: str()
          #site_long: str()
          #site_desc: str()
          #site_loc: str()
          #site_web: str()
          #site_security_email: str()
          #site_support_email: str()
          #site_other_grid: str()
          bdii_host: str()
          use_argus: str()
          ce_host: str()
          globus_tcp_port_range: str()
          ce_batch_sys: str()
          ce_capability: str()
          ce_cpu_model: str()
          ce_cpu_speed: str()
          ce_cpu_vendor: str()
          ce_inboundip: str()
          ce_logcpu: str()
          ce_minphysmem: str()
          ce_minvirtmem: str()
          ce_os: str()
          ce_os_arch: str()
          ce_os_release: str()
          ce_os_version: str()
          ce_otherdescr: str()
          ce_outboundip: str()
          ce_physcpu: str()
          ce_runtimeenv: str()
          ce_sf00: str()
          ce_si00: str()
          ce_smpsize: str()
          batch_server: str()
          job_manager: str()
          ce_batch_sys: str()
          batch_log_dir: str()
          batch_version: str()
          blparser_with_updater_notifier: str()
          blparser_host: str()
          cemon_host: str()
          cream_db_user: str()
          cream_db_password: str()
          apel_mysql_host: str()
          apel_db_password: str()
          ce_close_se: str()
          ce_close_se3_access_point: str()
          ce_close_se3_host: str()
          se_list: str()
          se_mount_info_list: str()
          vo_sw_dir: str()
          vos: str()
          queues: str()
          alice_group_enable: str()
          vo_alice_default_se: str()
          vo_alice_queues: str()
          vo_alice_storage_dir: str()
          vo_alice_sw_dir: str()
          vo_alice_voms_servers: str()
          vo_alice_vomses: str()
          vo_alice_voms_ca_dn: str()
          dteam_group_enable: str()
          vo_dteam_sw_dir: str()
          vo_dteam_default_se: str()
          vo_dteam_storage_dir: str()
          vo_dteam_voms_servers: str()
          vo_dteam_vomses: str()
          vo_dteam_voms_ca_dn: str()
          ops_group_enable: str()
          vo_ops_sw_dir: str()
          vo_ops_default_se: str()
          vo_ops_storage_dir: str()
          vo_ops_vomses: str()
          vo_ops_voms_ca_dn: str()
          vo_ops_voms_servers: str()
      - supplemental_config: 
          some_additional_parameter: some_value
        

supported_virtual_organizations: 
  - *default_vo_alice
  - *default_vo_dteam
  - *default_vo_ops

groups:
  - gid: 1395
    name: *default_group_alice_name
    accepted_voms_extensions:   
      vo: 'alice' # add_vo_name_in_default_config
      group: ''
      role: '' 
      category: ''
  - gid: 1397
    name: *default_group_alicesgm_name
    priority_group: sgm
    accepted_voms_extensions: '/alice/ROLE=lcgadmin'
  - *default_group_dteam
  - *default_group_dteamsgm
  - *default_group_ops
  - <<: *default_group_opssgm
    gid: 2018
  
pool_accounts: 
  - base_name: 'alice'
    initial_uid: '10417'
    users_num: '5'
    primary_group: *default_group_alice_name
  - base_name: 'sgmali'
    initial_uid: '60101'
    users_num: '10'
    primary_group: *default_group_alicesgm_name
    secondary_group: *default_group_alice_name
  - *default_pool_account_dteam_with_sgm
  - *default_pool_account_ops_with_sgm

